### ISSUE TITLE
Using Search 'fields' option returns undefined 

### ISSUE THREAD

**Issue by griojas** [jenjinstudios/jira-connector#2]
Whenever i call the search method and pass along jql and fileds, i get a undefined. 

Here the call:

jira.search.search({jql: 'issuetype in(Story,Bug,Issue) AND status not in("Resolved","Closed") AND sprint in openSprints()', fields: 'summary,status' }, function(err, res) { console.log(res);});

Whenever i omit the 'fields' option, it works like a charm.

**Comment by floralvikings** [comment]
The fields parameter is actually an array, rather than a comma separated string; that's probably what's causing the issue.

Try using this, instead:

```javascript
jira.search.search( {
    jql: 'issuetype in(Story,Bug,Issue) AND status not in("Resolved","Closed") AND sprint in openSprints()', 
    fields: ['summary', 'status']
  }, 
  function(err, res) { console.log(res); }
);
```

**Comment by floralvikings** [comment]
@griojas Did using an array instead of the comma separated string fix your problem?
